### ISSUE TITLE
Can it target elastic search?

### ISSUE THREAD

**Issue by justinmchase** [blackevil245/serverless-subscription-filter#1]
When setting up my subscription filter, I would like to plumb my logs up to an elastic search instance instead of another lambda. Is that possible with this plugin?

To be clear I am able to do this manually in the dashboard with a few clicks and I already have an Elastic Search instance setup. I'm just wondering if all of that is in place, is it as simple as providing the correct name / arn?

**Comment by justinmchase** [comment]
It seems that when I first connected my logs to ES it just created a lambda for me, which just puts the log entries into ES. So that means that these logs just trigger lambdas and so this _will_ actually do what I need. Thanks.

**Comment by hieuunguyeen** [comment]
@justinmchase glad it was able to help you :)
